### ISSUE TITLE
Dixon-Price function: flatten input X before doing other computations

### ISSUE THREAD

**Issue by llguo95** [bessagroup/F3DASM#111]
https://github.com/bessagroup/F3DASM/blob/56d5f10f46efe65c9f519bbfafedcb568722b63b/src/f3dasm/functions/pybenchfunction.py#L939

**Comment by llguo95** [comment]
add 
X = X.flatten()
before line 939

**Comment by mpvanderschelling** [comment]
Can you provide me with an explanation why this should be implemented? The `evaluate(self, X)` function always expects an 1D-array in the newest `pr/1.0` commits:

https://github.com/bessagroup/F3DASM/blob/c0068ca0f1f5a796d82a94325e2ec42b999b845e/src/f3dasm/functions/function.py#L65

**Comment by llguo95** [comment]
I stand corrected; it's not needed! 
I accidentally added another axis to my input data when I was trying to evaluate a function at it.
Closing this issue!
