### ISSUE TITLE
Add a description attribute to parameters

### ISSUE THREAD

**Issue by GuillaumeBroggi** [bessagroup/f3dasm#130]
https://github.com/bessagroup/f3dasm/blob/0cf16d00463e449f82e6f8b3f5bf061ecae7cdd2/src/f3dasm/design/parameter.py#L23-L33

`name` alone might not be sufficient to describe unambigously a parameter.

**Comment by mpvanderschelling** [comment]
This class is supposed to be an interace class and should not be created directly
