### ISSUE TITLE
Advanced discrete parameter (from a list, with a step != 1, etc.)

### ISSUE THREAD

**Issue by GuillaumeBroggi** [bessagroup/f3dasm#131]
### Motivation

It can be useful to specify discrete numerical parameters that do not include every values from the lower to upper bound.

Categorical parameters provide a similar functionality, but for strings, and from a design point of view, a discrete parameter restricted to some values is not a categorical parameter.

### Description

The feature could be implemented by implementing a new discrete parameter class (or updating the existing one) that can be constructed with a list, like the categorical parameters. 

An additional argument `step` could also be implemented for the exiting class.

**Comment by mpvanderschelling** [comment]
The `Domain.add_category` method accepts an Iterable of values. These values can be arbitrary, so the functionality that you describe has been implemented!

A step method has been implemented as an optional argument of the `Domain.add_int` method. The default stepsize is 1
