### ISSUE TITLE
experimentdata can not read from csv file

### ISSUE THREAD

**Issue by JiaxiangYi96** [bessagroup/f3dasm#221]
when I am using f3dsm to get my experimentdata from file, it does't work.  So the issue is    
 ""
file_path = Path('/home/jiaxiangyi/Documents/rvesimulator/examples/cddm/f3dasm_integration/design_of_experiments.csv')
data = f3dasm.ExperimentData.from_file(filename=file_path)
"" 
If I ran the above code, I will receive en error that "file is not found" and if I delete the ".csv" at the very end, it also showed the same error. The "design_of_experiments.csv" file is in the path. I can use pandas.read_csv to retrive it, but with f3dasm it does't work.

**Comment by mpvanderschelling** [comment]
Hey Yaga,

I'll update the documentation about the `from_file` method. The `from_file` method is for loading the `ExperimentData` when you have already created the ExperimentData object before and stored it to disk. It requires you to have `<name>_input.csv`, `<name>_output.csv`, `<name>_domain.pkl` and `<name>_jobs.pkl` files already.

If you want to load the input data and/or output data from a csv file, you can do that by constructing the object and giving the name of the .csv file:

```
experimentdata = Experimentdata(input_data='path/to/inputdata.csv', output_data='path/to/outputdata.csv')
```

**Comment by JiaxiangYi96** [comment]
thanks, I will try it out
