### ISSUE TITLE
Sphinx Gallery problem with TOC headers

### ISSUE THREAD

**Issue by mpvanderschelling** [bessagroup/f3dasm#274]
## Problem
In the tutorial doc part, all the tutorial pages go into the last section.

<img width="306" alt="350861721-430b43a5-3fa4-44d2-b779-b76c945fbe4b" src="https://github.com/user-attachments/assets/6996842b-41ea-4b88-a3d3-ba56925f4666">

## Possible solution

This might be some header-issue when generating the Sphinx Gallery

**Comment by RMeli** [comment]
https://github.com/openjournals/joss-reviews/issues/6912

**Comment by mpvanderschelling** [comment]
Fixes by adding the `sphinx_gallery_conf` option `nested_sections=False`. See [here](https://sphinx-gallery.github.io/stable/configuration.html#nesting-gallery-sections) for explanation
