### ISSUE TITLE
Declare sampling method in DoE parameters

### ISSUE THREAD

**Issue by manuGil** [bessagroup/F3DASM#38]
Implement declaration of sampling method as part of each DoE parameter:
Example:
```
vars ={ salib_solob({'f11': [1,2] ..... , n=10}),
materil: {}
}
```

The above syntax is not possible, because, in Python, a dictionary must define **key:value** pairs. This means that the above example has to be translated in something like: `vars = {"param1": salib_sobol( { 'f11':[1,2]...., n=10} ), material: {} }`. In other words, we will have to define a key for every parameter that aims to use a sampling method. This will make the whole dictionary difficult to pars and distinguish which keys are names for the columns of the data frame, and which keys aren't. 
Below, I propose some options to deal with this issue considering the less impact on the current code base. **Any suggestions or ideas on a better way to deal with this?**

**Comment by manuGil** [comment]
To implement this change, we need to change the way we declare the variable for a DoE. 
There are a couple of options, and each of them has an impact on how much the current code for sampling and creating  a flat pandas data frame:

### Option 1:
Keep the current sampling code relatively unchanged. This means that we can define a sampling method for a list of variables or for a single variable as long as we do it in this way: `SALibSobol(size, <dictionary with ranges for sampling>)`

This requires changing the way we declare variables for a DoE as a list that contains, arrays (samples), dictionaries, other lists, and other dictionaries. Example:
```python
VARS = [
        SALibSobol(5, {'F11':[-0.15, 1], 'F12':[-0.1,0.15], 'F22':[-0.2, 1]}),
        SALibSobol(2, {'radius': [0.3, 0.5]}),
        {'material1': 
            {'STEEL': [
                SALibSobol(4, {'E': [1,100]}), 
                {'u': [0.1, 0.2, 0.3] } 
                ],
            'CARBON': [ 
                {'E': 5}, 
                {'u': 0.5}, 
                {'s': 0.1 } 
                ]     
            } 
        },
        {'material2': 
            {'CARBON': [
                {'x': 2}
                ] 
            }
        }
        ]   
```

**Pros:**
+ No need to change the sampling classes and method

**Cons:**
- The definition of the variables might look messy and not intuitive at first sight.
- Requires to change the methods to produce a flat data frame

**Comment by manuGil** [comment]
### Option 2
Use a prefix for every parameter that is attached to a sampling method to maintain the structure of a dictionary. For example: `SALibSobol(size, <dictionary with ranges for sampling>)` must become `"sample1": SALibSobol(size, <dictionary with ranges for sampling>)`
Example:

```python
vars = {'sample1': SalibSobol(5, {'F11':[-0.15, 1], 'F12':[-0.1,0.15], 'F22':[-0.2, 1]}),
            'sample2': SalibSobol(2, {'radius': [0.3, 0.5]}),
            'material1': 
                {'STEEL': {
                    'sample3': SalibSobol(4, {'E': [1,100]}), 
                    'u': [0.1, 0.2, 0.3] } 
                },
                'CARBON': { 
                    'E': 5, 
                    'u': 0.5, 
                    's': 0.1  
                }, 
            'material2': { 
                'CARBON':  {
                    'x': 2
                }
            }
            }
```

**Pros:**
+ A dictionary structure is maintained across the definition of parameters.
+ Will be easier for a user to find and modify a parameter using build-in functions to handle dictionaries. 
+ The definition is more compact (less typing) and might be more intuitive (users don't have to remember which parts of the definition must be a list, and which parts dictionaries; with the exception of vector values)

**Cons:**
- For simplicity in the implementation, the user must always use the prefix `sample` to name parameters with a sampling method. At the same level of the tree structure, no two-parameter can use the same name.
Requires to change the methods to produce a flat data frame, but this will be the case for any other change to the definition of the variables.

**Comment by manuGil** [comment]
After looking into how to parse a dictionary as given in **Option 2**, the con doesn't hold anymore. The user will be able to give custom names to parameters that contain a sampling method.  So that:
```python
vars = {'myparam': SalibSobol(5, {'F11':[-0.15, 1], 'F12':[-0.1,0.15], 'F22':[-0.2, 1]}),
            'mysample': SalibSobol(2, {'radius': [0.3, 0.5]}),
            'material1': .......
}
```

**Comment by manuGil** [comment]
@mabessa **Can I have an example of the full list of parameters for the case of hyperelastic experiments?** From the previous version, I get the Fs, Lc, geometry, Vf, and radius (or other geometric parameters), but I am missing an actual definition for the materials.

**Comment by mabessa** [comment]
I like option 2.

Concerning the material parameters for the example, you can use the same used by Taylan. One phase can be the NeoHookean material (needing parameter E and parameter nu) and the other the SaintVenant material (also needing parameter E and nu). The NeoHookean could be for the particles, assuming E=[500,2000] and nu=0.4, while the other could be the matrix with E=[5,200] and nu=0.3. If you have additional questions, please reach out to me in person about this. Thanks!
