### ISSUE TITLE
python 3 libraries compatible with abaqus python 2

### ISSUE THREAD

**Issue by AmosJoseph** [bessagroup/F3DASM#4]
Excuse me,do you encounter the problem of  compatiblity?
 
You seem to use abaqus python script and python 3 libraries.

Now abaqus uses python 2,but most libraries are python 3,how to integrate  abaqus python script with python 3 libraries? They are often uncompatible.

Best!

**Comment by lpereira95** [comment]
Dear @AmosJoseph, 

First of all, thank you for your interest in F3DASM. I hope you are able to use it to solve your own problems.

If fact, abaqus uses python 2, and everything that is done in our abaqus scripts uses python 2 only (and only the libraries already included in abaqus, even if it is possible to add new libraries).

The code you see that is written in python 3 relates to everything that is done outside abaqus (or any other solver/software), such as design of experiments, managing of simulations (i.e. which simulations to run, parallelization of simulations, where to store the generated data), post-processing and machine learning.

I hope I answered your question!
