### ISSUE TITLE
Same name for parameters when creating design space

### ISSUE THREAD

**Issue by SNMS95** [bessagroup/F3DASM#70]
```
x0 = f3dasm.ContinuousParameter(name='x0', lower_bound=-1.0, upper_bound=1.0)
x1= f3dasm.ContinuousParameter(name='x0', lower_bound=-1.0, upper_bound=1.0)
```

Accessing samples by
```
rsampler = f3dasm.sampling.RandomUniformSampling(design, seed)
samples_random = rsampler.get_samples(30)
```
 causes the following error:
`"KeyError: "Only a column name can be used for the key in a dtype mappings argument. '('input', 'x0')' not found in columns."`

It would be nice if the error is more helpful!

**Comment by mpvanderschelling** [comment]
I've fixed this issue by raising an error if you add parameters with the same name to a design space!
