### ISSUE TITLE
Sampler random seed

### ISSUE THREAD

**Issue by SNMS95** [bessagroup/f3dasm#71]
```
rsampler = f3dasm.sampling.RandomUniformSampling(design, seed = 5)
samples_random = rsampler.get_samples(2)
```
gives the result
![image](https://user-images.githubusercontent.com/72760812/202544462-92b407a1-5056-4783-9131-7f7d01f4b992.png)

If I run `samples_random = rsampler.get_samples(2)` again, it gives a different set of samples.
![image](https://user-images.githubusercontent.com/72760812/202544754-dc50a280-d40c-41bc-9e2a-30ac1d47594a.png)
 So wouldn't it make more sense to add the seed option to the `get_samples()` function instead ?

**Comment by mpvanderschelling** [comment]
I'll close this issue since it is no longer relevant to the current state of the project. The sampler classes are changed to string key-word arguments
