### ISSUE TITLE
Description for add_output()

### ISSUE THREAD

**Issue by SNMS95** [bessagroup/f3dasm#72]
https://github.com/bessagroup/F3DASM/blob/82e42fdf00b5d3d5a58c33219cc8b75f45ef3c26/src/f3dasm/base/data.py#L51-L52

The name of the function might be misleading . I expected for the function to keep adding outputs (y1, y2 ..etc.) but instead it assigns values to the already created output space.

**Comment by mpvanderschelling** [comment]
This function is no longer available in version 1.3.0+
