### ISSUE TITLE
Best input parameters ? 

### ISSUE THREAD

**Issue by SNMS95** [bessagroup/f3dasm#73]
https://github.com/bessagroup/F3DASM/blob/82e42fdf00b5d3d5a58c33219cc8b75f45ef3c26/src/f3dasm/base/data.py#L123-L135

It is not clear if the function calculates the point closest to the global minima or the one  that is closest in value to the global minima.

**Comment by mpvanderschelling** [comment]
I have updated the documentation of the function `ExperimentData.get_n_best_output`.
