### ISSUE TITLE
Installation of f3dasm

### ISSUE THREAD

**Issue by h-vijayakumaran** [bessagroup/F3DASM#74]
I have faced errors during the installation of `f3dasm`, which made me dig into the installation a bit more in detail. The following suggestions wont necessarily fix the issue I am facing, but would definitely be a clean-up, and also make installation more straightforward for others.

# Comments on current instructions: For Linux

## Reg: _Preferred way_

I see that there are many (slightly more than usual) packages  in the `f3dasm_environment.yml` file, and probably these are packages that got installed as additional packages. If this is the case:
1. I recommend that the `yaml` file is exported as:
`conda env export -n f3dasm_env --from-history -f f3dasm_environment.yml`

2. Of course, this wouldn't list the `pip` installations. For that, do a regular export as:
`conda env export -n f3dasm_env  -f f3dasm_environment_pip.yml`

3. Manually update the `f3dasm_environment.yml` to have the `pip` installation list from `f3dasm_environment_pip.yml`

## Reg: _If things fail_
1. Minor documentation error: Before `pip install -e .` the environment has to be activated. So, 
```
conda activate f3dasm_env
pip install -e .
```
2. Importing `f3dasm` fails because `setup.py` doesn't install `tensorflow` as a dependency. I also see in that in `setup.py` there are some packages which the **preferred way** are installed through via `conda` .  It would be a good idea to separate out the `pip` installations and `conda` installations.  

3. Furthermore, it might be worth defining the version of the packages in the `setup.py`, unless it is left out on purpose.

## Reg: _Installing all packages manually_
1. Minor documentation error: Before `pip install -e .` the environment has to be activated. So, 
```
conda activate f3dasm_env
pip install -e .
```

# Suggested instruction: For Linux

If the **preferred way** and **if things fail** are updated as suggested above, the **Installing all packages manually** would become redundant. For **if things fail**,  I suggest that `conda` installations happens first, followed by installation through `setup.py`, which only installs packages that are additionally required (i.e. redundancies removed from `setup.py`).

**Comment by mpvanderschelling** [comment]
Hey Hari, thanks for your comments
I'm completely changing the way f3dasm is installed
This is because it is too complicated and is not working consistently on different OS
I'll show you how during the next coding practices session
