### ISSUE TITLE
add possibility to insert ONLY input numpy array (leave output array as NaNs)

### ISSUE THREAD

**Issue by llguo95** [bessagroup/f3dasm#77]
```
    # TODO: add possibility to insert ONLY input numpy array (leave output array as NaNs)
```

https://github.com/bessagroup/F3DASM/blob/18591237720e370bbb295de823888bb3f7dd8649/src/f3dasm/base/data.py#L63

**Comment by mpvanderschelling** [comment]
This functionality is present now: you can create the `ExperimentData` object without explicitly give an `output_data` argument
