### ISSUE TITLE
Correct names to StyblinskiTang

### ISSUE THREAD

**Issue by llguo95** [bessagroup/F3DASM#87]
```
class StyblinskiTank(PyBenchFunction): #TODO: Correct names to StyblinskiTang
```

https://github.com/bessagroup/F3DASM/blob/18591237720e370bbb295de823888bb3f7dd8649/src/f3dasm/functions/pybenchfunction.py#L2579

**Comment by mpvanderschelling** [comment]
fixed bugs #78 to #87 with latest commit
