### ISSUE TITLE
Naming function parameter as "input"

### ISSUE THREAD

**Issue by SNMS95** [bessagroup/F3DASM#93]
### Motivation

https://github.com/bessagroup/F3DASM/blob/f14330ea61d928f19b3b866a380611822055639a/src/f3dasm/design/experimentdata.py#L93  

 def add_numpy_arrays(self, input: np.ndarray, output: np.ndarray):
....

- The work **input** is a keyword

### Suggestion

Would be better to change it from  "input" to another name as per our Code of conduct.

**Comment by mpvanderschelling** [comment]
I've fixed this issue and created a pull request to the `pr/1.0` branch. I added @SNMS95 as a reviewer!
